services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - backend_uploads:/app/uploads
      - backend_data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - log-dashboard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=tenexai
      - JWT_SECRET=supersecretkey
    restart: unless-stopped
    networks:
      - log-dashboard-network

volumes:
  backend_uploads:
    driver: local
  backend_data:
    driver: local

networks:
  log-dashboard-network:
    driver: bridge 